
--CREATE DATABASE MOVIMENTACAO;

--USE MOVIMENTACAO;

--CREATE TABLE CLIFOR(
--IDCLIFOR  INT PRIMARY KEY IDENTITY(1,1),
--NOME VARCHAR(200) NOT NULL,
--ENDERECO VARCHAR(200) NOT NULL,
--TELEFONE VARCHAR(15),
--CNPJ VARCHAR(30) UNIQUE NOT NULL
--)

--INSERT INTO CLIFOR (NOME, ENDERECO, CNPJ) VALUES ('Dona Cida e Seu Zé', 'R: das Ofelias, 131 Atibaia - SP', 'XXX.XXX.XXX-XX');

SELECT * FROM CLIFOR  

