//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReqMateriaisRmTotvs.WSConsultar {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.totvs.com.br/br/", ConfigurationName="WSConsultar.wsConsultaSQLSoap")]
    public interface wsConsultaSQLSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.totvs.com.br/br/AutenticaAcessoAuth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutenticaAcessoAuth(string Usuario, string Senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.totvs.com.br/br/AutenticaAcessoAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutenticaAcessoAuthAsync(string Usuario, string Senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.totvs.com.br/br/AutenticaAcesso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutenticaAcesso();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.totvs.com.br/br/AutenticaAcesso", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutenticaAcessoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.totvs.com.br/br/RealizarConsultaSQLDataTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RealizarConsultaSQLDataTable(string codSentenca, int codColigada, string codSistema, string codUsuario, string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.totvs.com.br/br/RealizarConsultaSQLDataTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> RealizarConsultaSQLDataTableAsync(string codSentenca, int codColigada, string codSistema, string codUsuario, string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.totvs.com.br/br/RealizarConsultaSQLDataTableAuth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RealizarConsultaSQLDataTableAuth(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.totvs.com.br/br/RealizarConsultaSQLDataTableAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> RealizarConsultaSQLDataTableAuthAsync(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.totvs.com.br/br/RealizarConsultaSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RealizarConsultaSQL(string codSentenca, int codColigada, string codAplicacao, string codUsuario, string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.totvs.com.br/br/RealizarConsultaSQL", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RealizarConsultaSQLAsync(string codSentenca, int codColigada, string codAplicacao, string codUsuario, string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.totvs.com.br/br/RealizarConsultaSQLAuth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RealizarConsultaSQLAuth(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.totvs.com.br/br/RealizarConsultaSQLAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RealizarConsultaSQLAuthAsync(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsConsultaSQLSoapChannel : ReqMateriaisRmTotvs.WSConsultar.wsConsultaSQLSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsConsultaSQLSoapClient : System.ServiceModel.ClientBase<ReqMateriaisRmTotvs.WSConsultar.wsConsultaSQLSoap>, ReqMateriaisRmTotvs.WSConsultar.wsConsultaSQLSoap {
        
        public wsConsultaSQLSoapClient() {
        }
        
        public wsConsultaSQLSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsConsultaSQLSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsConsultaSQLSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsConsultaSQLSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AutenticaAcessoAuth(string Usuario, string Senha) {
            return base.Channel.AutenticaAcessoAuth(Usuario, Senha);
        }
        
        public System.Threading.Tasks.Task<string> AutenticaAcessoAuthAsync(string Usuario, string Senha) {
            return base.Channel.AutenticaAcessoAuthAsync(Usuario, Senha);
        }
        
        public string AutenticaAcesso() {
            return base.Channel.AutenticaAcesso();
        }
        
        public System.Threading.Tasks.Task<string> AutenticaAcessoAsync() {
            return base.Channel.AutenticaAcessoAsync();
        }
        
        public System.Data.DataTable RealizarConsultaSQLDataTable(string codSentenca, int codColigada, string codSistema, string codUsuario, string parameters) {
            return base.Channel.RealizarConsultaSQLDataTable(codSentenca, codColigada, codSistema, codUsuario, parameters);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> RealizarConsultaSQLDataTableAsync(string codSentenca, int codColigada, string codSistema, string codUsuario, string parameters) {
            return base.Channel.RealizarConsultaSQLDataTableAsync(codSentenca, codColigada, codSistema, codUsuario, parameters);
        }
        
        public System.Data.DataTable RealizarConsultaSQLDataTableAuth(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters) {
            return base.Channel.RealizarConsultaSQLDataTableAuth(codSentenca, codColigada, codAplicacao, Usuario, Senha, parameters);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> RealizarConsultaSQLDataTableAuthAsync(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters) {
            return base.Channel.RealizarConsultaSQLDataTableAuthAsync(codSentenca, codColigada, codAplicacao, Usuario, Senha, parameters);
        }
        
        public string RealizarConsultaSQL(string codSentenca, int codColigada, string codAplicacao, string codUsuario, string parameters) {
            return base.Channel.RealizarConsultaSQL(codSentenca, codColigada, codAplicacao, codUsuario, parameters);
        }
        
        public System.Threading.Tasks.Task<string> RealizarConsultaSQLAsync(string codSentenca, int codColigada, string codAplicacao, string codUsuario, string parameters) {
            return base.Channel.RealizarConsultaSQLAsync(codSentenca, codColigada, codAplicacao, codUsuario, parameters);
        }
        
        public string RealizarConsultaSQLAuth(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters) {
            return base.Channel.RealizarConsultaSQLAuth(codSentenca, codColigada, codAplicacao, Usuario, Senha, parameters);
        }
        
        public System.Threading.Tasks.Task<string> RealizarConsultaSQLAuthAsync(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters) {
            return base.Channel.RealizarConsultaSQLAuthAsync(codSentenca, codColigada, codAplicacao, Usuario, Senha, parameters);
        }
    }
}
